name: Build wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        arch:
          - x86_64
          - aarch64
          - armv7
          - s390x
          - ppc64le
          - x86
        include:
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
        shell: bash

      - name: Install maturin
        run: pip install maturin

      - name: Install cross and QEMU (Linux)
        if: runner.os == 'Linux'
        run: |
          cargo install cross
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build wheel (x86_64 macOS)
        if: matrix.os == 'macos-latest' && matrix.arch == 'x86_64'
        run: |
          rustup target add x86_64-apple-darwin
          cd python/delta-kernel-python
          maturin build --release --target x86_64-apple-darwin
        shell: bash

      - name: Build wheel (ARM macOS)
        if: matrix.os == 'macos-latest' && matrix.arch == 'arm64'
        run: |
          rustup target add aarch64-apple-darwin
          cd python/delta-kernel-python
          maturin build --release --target aarch64-apple-darwin
        shell: bash


      - name: Build wheel (Linux)
        if: runner.os == 'Linux'
        run: |
          rustup target add ${{ matrix.arch }}
          cd python/delta-kernel-python
          cross build --release --target ${{ matrix.arch }}-unknown-linux-gnu
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: python/delta-kernel-python/target/${{ matrix.arch }}-unknown-linux-gnu/release/*.whl
